version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: sahaba
